[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
flipper = "GywSWhcnR1WDZgGSMd7Nev1ugyj99Cw1q3TSKvqEHKig"
openbookv_2_interface = "2VN914zCR1WkHwXeP8vRdimBWMYuNGL9MqJbbQ28SmMy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ctapang/.config/solana/id.json"

# To do "anchor run node", contracts must be deployed first
# deployment is necessary everytime when running in localnet
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
node = "node app/CreateMarket.js"
